version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Etc/UTC"
    target-branch: "master"
    labels: ["dependencies", "github-actions"]
    groups:
      actions-deps:
        patterns: ["*"]

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Etc/UTC"
    target-branch: "master"
    labels: ["dependencies", "python"]
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10

