name: Workflow Lint

on:
  push:
  pull_request:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run actionlint
        uses: raven-actions/actionlint@v2
        with:
          fail-on-error: true


